<a href="https://colab.research.google.com/github/happymondaynkanta/Tensorflow-Developer-Certificate-Course/blob/main/Section_2_19_21_tensor_fundamental.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Other ways to make tensors

Though you might rarely use these (remember, many tensor operations are done behind the scenes for you), you can use tf.ones() to create a tensor of all ones and tf.zeros() to create a tensor of all zeros

In [2]:
# import tensorflow library
import tensorflow as tf


<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)>

In [ ]:
# Let's create tensor of all ones
tf.ones(shape=(3,2))

In [3]:
# Let's create tensor of all ones
tf.zeros(shape=(3,2))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)>

# Turning Numpy array to Tensor

* You can also turn NumPy arrays in into tensors.

* Remember, the main difference between tensors and NumPy arrays is that tensors can be run on GPUs.

🔑 Note: A matrix or tensor is typically represented by a capital letter (e.g. X or A) where as a vector is typically represented by a lowercase letter (e.g. y or b).

# X = tf.constant(some_matrix)
# y = tf.constant(vector)

In [5]:
# import Numpy library
import numpy as np


🔑:This is how to create Numpy Array

In [9]:
numpy_A = np.arange(1, 25, dtype=np.int32)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

🔑: This is how to turn Numpy Array into Tensor

In [11]:

A = tf.constant(numpy_A)
A

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>

 Specifying the shape of the Tensor

In [7]:
numpy_A = np.arange(1, 25, dtype=np.int32)
A = tf.constant(numpy_A, shape=[2, 3, 4]) # you must pass the array you want to turn into tensor and you must specify the shape. Note the shape 2*3*4 has to match the number of element in the array
numpy_A, A

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32),
 <tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>)

# Getting information from tensors (shape, rank, size)

There will be times when you'll want to get different pieces of information from your tensors, in particuluar, you should know the following tensor vocabulary:

* Shape: The length (number of elements) of each of the dimensions of a tensor.
* Rank: The number of tensor dimensions. A scalar has rank 0, a vector has rank 1, a matrix is rank 2, a tensor has rank n.
* Axis or Dimension: A particular dimension of a tensor.
* Size: The total number of items in the tensor.

You'll use these especially when you're trying to line up the shapes of your data to the shapes of your model. For example, making sure the shape of your image tensors are the same shape as your models input layer.

We've already seen one of these before using the ndim attribute. Let's see the rest.

Let's create a Rank 4 Tensor of Zeros using the function "tf.zeros()"

In [12]:
# Rank 4 Tensor is a 4-dimensional Tensor
rank_4_tensor = tf.zeros([2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

Let's create a Rank 4 Tensor of Ones using the function "tf.zeros()"

In [13]:
# Rank 4 Tensor is a 4-dimensional Tensor
rank_4_tensor_1 = tf.ones([2,3,4,5])
rank_4_tensor_1

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]],


       [[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]]], dtype=float32)>

## Getting Information from our different Tensors created

In [14]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [15]:
rank_4_tensor_1.shape, rank_4_tensor_1.ndim, tf.size(rank_4_tensor_1)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

Let Extract Different Attributes from Our Tensor in a more organized pattern

In [16]:
# get the various attribute of the tensors
print("Datatype of every element:", rank_4_tensor.dtype )
print("Number of dimension:", rank_4_tensor.ndim )
print("Element along axis 0 of tensor:", rank_4_tensor.shape[0] )
print("Element along the last axis of tensor:", rank_4_tensor.shape[-1] )
print("shape of the tensor:", rank_4_tensor.shape )
print("Total number of elements in the tensor:", tf.size(rank_4_tensor))
print("Total number of elements in the tensor in numpy format:", tf.size(rank_4_tensor).numpy()) # This will convert to numpy

Datatype of every element: <dtype: 'float32'>
Number of dimension: 4
Element along axis 0 of tensor: 2
Element along the last axis of tensor: 5
shape of the tensor: (2, 3, 4, 5)
Total number of elements in the tensor: tf.Tensor(120, shape=(), dtype=int32)
Total number of elements in the tensor in numpy format: 120


# Indexin Tensor

* You can also index tensors just like Python lists

In [17]:

# First we create our Tensor
# Rank 4 Tensor is a 4-dimensional Tensor
rank_4_tensor = tf.zeros([2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [18]:
# Get the first 2 items of each dimension
rank_4_tensor[:2, :2, :2, :2]


<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [19]:
# Get the first 3 items of each dimension
rank_4_tensor[:3, :3, :3, :3]

<tf.Tensor: shape=(2, 3, 3, 3), dtype=float32, numpy=
array([[[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]]], dtype=float32)>

In [20]:
# Get the dimension of eeach index 
rank_4_tensor[:1, :1, :1, :1]

<tf.Tensor: shape=(1, 1, 1, 1), dtype=float32, numpy=array([[[[0.]]]], dtype=float32)>

In [21]:
# Get the dimension from each index except for the final one
rank_4_tensor[:1, :1, :1, :]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [22]:
# Get the dimension from each index except for the first one
rank_4_tensor[:, :1, :1, :1]

<tf.Tensor: shape=(2, 1, 1, 1), dtype=float32, numpy=
array([[[[0.]]],


       [[[0.]]]], dtype=float32)>

In [23]:
# Get the dimension from each index except for the second one
rank_4_tensor[:1, :, :1, :1]

<tf.Tensor: shape=(1, 3, 1, 1), dtype=float32, numpy=
array([[[[0.]],

        [[0.]],

        [[0.]]]], dtype=float32)>

# We want to create Tensor using the function "tf.constant" and the index the tensor

In [24]:
# Create a rank 2 tensor (2 dimensions) 
rank_2_tensor = tf.constant([[12, 5],
                             [8, 2]])
rank_2_tensor



<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[12,  5],
       [ 8,  2]], dtype=int32)>

In [30]:
# Get the first item of each row
rank_2_tensor[:, 0]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([12,  8], dtype=int32)>

In [31]:
# Get the last item of each row
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([5, 2], dtype=int32)>

# You can also add dimensions to your tensor whilst keeping the same information present using tf.newaxis.

* Adding an extra dimension to our tensor

In [32]:
# First we will create the 2-dimensional tensor
rank_2_tensor = tf.constant([[12, 5],
                             [8, 2]])
rank_2_tensor  # shape (2, 2),


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[12,  5],
       [ 8,  2]], dtype=int32)>

In [33]:
# secondly, we will add an extra dimension (to the end)
rank_3_tensor = rank_2_tensor[..., tf.newaxis] # in Python "..." means "all dimensions prior to"
rank_3_tensor #shape (2, 2, 1)

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[12],
        [ 5]],

       [[ 8],
        [ 2]]], dtype=int32)>

In [34]:
rank_2_tensor, rank_3_tensor # shape (2, 2) and  shape (2, 2, 1)

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[12,  5],
        [ 8,  2]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
 array([[[12],
         [ 5]],
 
        [[ 8],
         [ 2]]], dtype=int32)>)

You can achieve the same using tf.expand_dims().

In [35]:
tf.expand_dims(rank_2_tensor, axis=-1) # "-1" means last axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[12],
        [ 5]],

       [[ 8],
        [ 2]]], dtype=int32)>

In [36]:
tf.expand_dims(rank_2_tensor, axis=0) # "-1" means last axis

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[12,  5],
        [ 8,  2]]], dtype=int32)>