<a href="https://colab.research.google.com/github/happymondaynkanta/Tensorflow-Developer-Certificate-Course/blob/main/section_2_16_18_tensor_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Creating Tensor wit tf.variable()

In [1]:
# import tensorflow library
import tensorflow as tf

In [4]:
# creating the same tensor with tf.variable() as with tf.constant()
c_tensor = tf.Variable([10, 7])
unc_tensor = tf.constant([10, 7])
c_tensor, unc_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

 # Changing elements in our chanageable tensor

In [7]:
# let's try and change the first elemnet in our changeable tensor using the function .assign()
c_tensor[0].assign(7) # we want to change the first index from 10 -> 7
c_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [8]:
# let's try and change the second elemnet in our changeable tensor using the function .assign()
c_tensor[1].assign(10) # we want to change the second index from 7 -> 10
c_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([ 7, 10], dtype=int32)>

#### The function .assign() is not an attribute for unchangeable tensors. Unchageable tensors are tensors created using the function tf.constant()

##### 🔑 Note: Rarely in practice will you need to decide whether to use tf.constant or tf.Variable functions to create tensors, as Tensorflow does this you. However, if in doubt, use tf.constant and change it later if needed

# Creating Random Tensors

#### Random tensors are tensors of some arbitrary size which contains random number

In [12]:
# creating two random tensor (but are the same)
random_1 = tf.random.Generator.from_seed(42) # the seed is set for reproducibility
random_1 = random_1.normal(shape=(3,2))
random_2 = tf.random.Generator.from_seed(42) # the seed is set for reproducibility
random_2 = random_2.normal(shape=(3,2))


results of the generated random tensor

In [13]:
random_1, random_2 

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>)

Are the tensors equal?

In [14]:
random_1 == random_2 

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True],
       [ True,  True]])>

Let's change the value of the seed

In [17]:
# creating two random tensor (but are the same)
random_1 = tf.random.Generator.from_seed(7) # the seed is set for reproducibility
random_1 = random_1.normal(shape=(3,2))
random_2 = tf.random.Generator.from_seed(7) # the seed is set for reproducibility
random_2 = random_2.normal(shape=(3,2))

random_1, random_2, random_1 == random_2 

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.3240396 ,  0.28785667],
        [-0.8757901 , -0.08857018],
        [ 0.69211644,  0.84215707]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.3240396 ,  0.28785667],
        [-0.8757901 , -0.08857018],
        [ 0.69211644,  0.84215707]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

What if we make the seed value different?

In [18]:
# creating two random tensor (but are different)
random_1 = tf.random.Generator.from_seed(42) # the seed is set for reproducibility
random_1 = random_1.normal(shape=(3,2))
random_2 = tf.random.Generator.from_seed(7) # the seed is set for reproducibility
random_2 = random_2.normal(shape=(3,2))

random_1, random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.3240396 ,  0.28785667],
        [-0.8757901 , -0.08857018],
        [ 0.69211644,  0.84215707]], dtype=float32)>)

Are the tensors EQUAL?

In [19]:
random_1 == random_2 

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[False, False],
       [False, False],
       [False, False]])>

 # Shuffle the order of elements in a Tensor

In [21]:
# shuffle a tensor (this is valuable when you you want to shuffle your dataset so that the inherent order does not affect the learning)
tensor_1 = tf.constant([[10, 7], [8, 5], [3, 2]])
tensor_1

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 8,  5],
       [ 3,  2]], dtype=int32)>

Let's shuffle the tensor we have created

In [34]:
tf.random.shuffle(tensor_1)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 8,  5],
       [10,  7],
       [ 3,  2]], dtype=int32)>

What happens if we set the value of the operational seed?
The element in the tensor shuffles each time we run the operation

In [63]:
tf.random.shuffle(tensor_1, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 8,  5],
       [ 3,  2],
       [10,  7]], dtype=int32)>

What happens if we introduce a global and operational seed values?
The elements in the tensor do not shuffle. 

In [58]:
tf.random.set_seed(42) # this is the global randm seed
tf.random.shuffle(tensor_1) # this is the operational random seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 8,  5],
       [ 3,  2],
       [10,  7]], dtype=int32)>