Section 2_22: **Manipulating tensors (tensor operations)**

Manipulating tensors (tensor operations)
Finding patterns in tensors (numberical representation of data) requires manipulating them.

Again, when building models in TensorFlow, much of this pattern discovery is done for you.

Basic operations
You can perform many of the basic mathematical operations directly on tensors using Pyhton operators such as, +, -, *,/.

In [ ]:
# You can add values to a tensor using the addition operator

import tensorflow as tf
tensor = tf.constant([[10, 7], [3, 4]])
tensor + 10  #tensor = tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [ ]:
# Remember that the Original tensor is unchanged
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [ ]:
# Multiplication (known as element-wise multiplication)
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [ ]:
# Subtraction
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [ ]:
# Use the tensorflow built-in function equivalent of the '*' (multiply) operator
# The buit-in operation of tensor speedily up more faster while using GPU.
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [ ]:
# The original tensor is still unchanged
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

**Section 2-23: Matrix multiplication with tensor part 1**

One of the most common operations in machine learning algorithms is matrix multiplication.

TensorFlow implements this matrix multiplication functionality in the tf.matmul() method.

The main two rules for matrix multiplication to remember are:

Rule 1: The inner dimensions must match:

(3, 5) @ (3, 5) won't work\
(5, 3) @ (3, 5) will work\
(3, 5) @ (5, 3) will work\

Rule 2:The resulting matrix has the shape of the outer dimensions:

(5, 3) @ (3, 5) -> (5, 5)\
(3, 5) @ (5, 3) -> (3, 3)\
🔑 Note: '@' in Python is the symbol for matrix multiplication.

In [ ]:
# Matrix multiplication in TensorFlow
print(tensor)
tf.matmul(tensor, tensor)

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [ ]:
# Matrix multiplication with Python operator '@'
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [ ]:
# Create (3, 2) tensor
X = tf.constant([[1, 2],
                 [3, 4],
                 [5, 6]])

# Create another (3, 2) tensor
Y = tf.constant([[7, 8],
                 [9, 10],
                 [11, 12]])
X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [ ]:
# Try to matrix multiply them (will error) because the 3 * 2 is not equal to 3*2 matrrix form (different shapes)
X @ Y

InvalidArgumentError: ignored

Trying to matrix multiply two tensors with the shape (3, 2) errors because the inner dimensions don't match.

We need to either:

Reshape X to (2, 3) so it's (2, 3) @ (3, 2).

Reshape Y to (3, 2) so it's (3, 2) @ (2, 3).

We can do this with either:

tf.reshape() - allows us to reshape a tensor into a defined shape.
tf.transpose() - switches the dimensions of a given tensor.

In [ ]:
# Let's try tf.reshape() first.

# Example of reshape (3, 2) -> (2, 3)
tf.reshape(Y, shape=(2, 3))

SyntaxError: ignored