<a href="https://colab.research.google.com/github/happymondaynkanta/Tensorflow-Developer-Certificate-Course/blob/main/section_2_15_tensor_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Run tensorflow code using tf.function as a way to speed 
# regular python function

# Creating your first tensorflow code
# Introduction to tensor

In [1]:
# importing tensorflow
import tensorflow as tf



In [2]:
# verifying the tensorflow version
print(tf.__version__)


2.8.0


Creating the first tensor

In [3]:
# creating the first tensor with tf.constant()
scalar = tf.constant(7)
scalar


<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [4]:
# checking the dimension of tensor using ndim. ndim stands for the number of dimension
scalar.ndim

0

Creating a vector

In [5]:
# creating a vector
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [6]:
# checking for the dimension of the vector
vector.ndim

1

Creating a matric

In [10]:
# creating metric (metric has more than 1 dimension)
metric = tf.constant([[10, 9, 6], [9, 10, 7], [3,5, 2]])
metric

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[10,  9,  6],
       [ 9, 10,  7],
       [ 3,  5,  2]], dtype=int32)>

In [ ]:
# checking for the dimension of the metric
metric.ndim

In [18]:
# creating metric (metric has more than 1 dimension)
metric1 = tf.constant([[10, 9, 6], [9, 10, 7], [3,5, 2]], dtype =tf.float16) # specify the data type with float
metric1

<tf.Tensor: shape=(3, 3), dtype=float16, numpy=
array([[10.,  9.,  6.],
       [ 9., 10.,  7.],
       [ 3.,  5.,  2.]], dtype=float16)>

In [19]:
# checking for the dimension of the metric
metric1.ndim

2

Creating Tensor and check for its dimension. The number of tensor dimension is equal to the number of metric

In [16]:
# creating tensor using tf.constant()
tensor = tf.constant([[[2,4,5], [5,6,6]], [[9,7,8], [4,8,2]],[[7,1,3],[4,8,9]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[2, 4, 5],
        [5, 6, 6]],

       [[9, 7, 8],
        [4, 8, 2]],

       [[7, 1, 3],
        [4, 8, 9]]], dtype=int32)>

In [17]:
tensor.ndim

3

What I have created so far:
* Scalar: a single nmber
* Vector a number with direction
* Matric: 2-dimensional array of number
* Tensor: an n-dimensional array of number. Tensors are scalar, vector, and metric